### ISSUE TITLE
Add a configurable constraint for how far back in the past a skill event can be added

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#129]
Add a configurable constraint for how far back in the past a skill event can be added
- add service side and ui validation

**Comment by evenstensberg** [comment]
Any ideas of where this would go? Which files etc?

**Comment by mosefer** [comment]
I recommend acquainting yourself with the services, dashboard, and e2e-tests projects before diving in to making changes. If you're not already familiar from your previous contributions, [this](https://code.nsa.gov/skills-docs/contribution/devEnv.html) has steps to setup your local environment to run tests, etc.,

### Server Side
[UserSkillsController.addSkill](https://github.com/NationalSecurityAgency/skills-service/blob/f4bece04cda05c0efc9be3e20010051b11c2576f/service/src/main/java/skills/controller/UserSkillsController.java#L273) method would probably be a good place to add back-end validation
[Example of using configuration property](https://github.com/NationalSecurityAgency/skills-service/blob/f4bece04cda05c0efc9be3e20010051b11c2576f/service/src/main/java/skills/controller/UserSkillsController.java#L88) - Note that the property prefix needs to be ```skills.config.ui.``` so that it will be available on the client-side as well
[Where the integration test should go](https://github.com/NationalSecurityAgency/skills-service/blob/f4bece04cda05c0efc9be3e20010051b11c2576f/service/src/test/java/skills/intTests/reportSkills/ReportSkillsSpecs.groovy)

### Client Side
[Where the client-side validation should go](https://github.com/NationalSecurityAgency/skills-service/blob/f4bece04cda05c0efc9be3e20010051b11c2576f/dashboard/src/components/skills/AddSkillEvent.vue)
[Example of using config property in custom validator](https://github.com/NationalSecurityAgency/skills-service/blob/f4bece04cda05c0efc9be3e20010051b11c2576f/dashboard/src/components/skills/EditSkill.vue#L445)
[Where the E2E test should go](https://github.com/NationalSecurityAgency/skills-service/blob/f4bece04cda05c0efc9be3e20010051b11c2576f/e2e-tests/cypress/integration/skills_spec.js)

Thanks!

**Comment by dwalizer** [comment]
PR #1511

**Comment by mosefer** [comment]
@dwalizer - if the endpoint is called directly the client only receives a 400 error code without a response body explaining the constraint
