### ISSUE TITLE
'Project definitions comparison' metrics layout is not optimal if resized

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#194]
'Project definitions comparison' metrics when resized ends up wrapping 2nd column charts when there is proper space available for 2 columns

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/195

**Comment by mosefer** [comment]
@sudo-may I'm not entirely sure what the issue is here based off the description. If it's the side by side charts here:
![image](https://user-images.githubusercontent.com/61209506/101651291-e3bf9680-3a0a-11eb-9936-9ee3de4a0b0a.png)

it looks like the charts eventually wrap if the window size is decreased, however the charts won't display side by side again until the window size is increased substantially over the width that caused the charts to wrap.
