### ISSUE TITLE
Colons in the in a description are not shown

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2110]
- create a skill with a description that has colons, for example `some:value:it`
- view description in the Skills Display or Dashboard and colons are not shown - `somevalueit`

**Comment by dwalizer** [comment]
The issue is that the rich text editor expects text surrounded by colons to be emojis, so anything like `:this:` will be rendered differently.  However, if it's necessary to include text that has colons, this can be done by including it in a code block or other method.  The text is saved appropriately and regular colons are also displayed appropriately.  As such, there isn't anything for us to fix, as this is the intended behavior of the rich text editor.
