### ISSUE TITLE
I am unable to log in after a certain update

### ISSUE THREAD

**Issue by Nomango** [NationalSecurityAgency/skills-service#2119]
Hi, there. I am unable to log in after update from `v2.3.3` to `v2.4.3`. (But I tried again later in another environment and didn't encounter the problem, so strange! )

I am sure that the entered account and password is correct. The `performLogin` api returned a status code of 200 and a `JSESSIONID`. But the `userInfo` api returned null and a another `JSESSIONID` which is unexpected.

This causes the page to have no response after I click the login button.

![image](https://user-images.githubusercontent.com/22350366/230857552-a4568dae-f67d-41c7-b2cf-81e51d62d05d.png)

![image](https://user-images.githubusercontent.com/22350366/230857212-9f55f60c-0752-425d-a94c-ed1a3fdba939.png)

**Comment by Nomango** [comment]
The error logs:

```
INFO 9 --- [nio-8080-exec-2] skills.auth.UserInfoService              : Unexpected/Unauthenticated princial [anonymousUser]
```

**Comment by rmmayo** [comment]
Hello @Nomango - thank you for reporting this issue.  Question, are you running in a clustered environment, and if so are you storing the user session using JDBC or Redis?

**Comment by Nomango** [comment]
Yes! The problematic environment is a cluster.

I tried to use Redis to save sessions, but the issue still persists.

```
INFO 8 --- [nio-8080-exec-1] skills.auth.UserInfoService              : Unexpected/Unauthenticated princial [anonymousUser]
```

My env setting:

```yaml
SPRING_PROPS: " \
  spring.datasource.url=jdbc:postgresql://postgresql:5432/skills, \
  spring.datasource.username=skills, \
  spring.datasource.password=skillspass, \
  spring.session.store-type=redis, \
  spring.redis.host=redis, \
  spring.redis.port=6379, \
  spring.redis.password=, \
  spring.redis.database=4"
```

**Comment by Nomango** [comment]
I added session saving after the upgrade. Different error messages may appear for different versions here.

skills-service `v2.3.3` with `redis:5.0`:

```
INFO 8 --- [nio-8080-exec-1] skills.auth.UserInfoService              : Unexpected/Unauthenticated princial [anonymousUser]
```

When I checked Redis, I found that `spring:session:xxx` data was written to it.

skills-service `v2.4.3` with `redis:5.0`:

```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
```

I tried setting the redis host to `spring.redis.host=redis` or `spring.redis.host=host.docker.internal`, but the error message is still the same.

This time when I checked Redis, the data was empty.

**Comment by rmmayo** [comment]
Hi @Nomango - I think there may be something wrong with you Redis configuration.  Can you try storing the session using JDBC?  Could you please try adding the following properties:

```
    spring.session.store-type=jdbc
    spring.session.jdbc.initialize-schema=always
```

**Comment by Nomango** [comment]
> Hi @Nomango - I think there may be something wrong with your Redis configuration. Can you try storing the session using JDBC?
> 
> Could you please try adding the following properties:
> 
> ```
>     spring.session.store-type=jdbc
>     spring.session.jdbc.initialize-schema=always
> ```

`jdbc` session is working properly for me.

Maybe there is something wrong with redis session? I feel that my configuration is correct.

```bash
$ docker exec -t skilltree cat /application.properties
spring.datasource.url=jdbc:postgresql://postgresql:5432/skills
spring.datasource.username=skills
spring.datasource.password=skillspass
spring.session.store-type=redis
spring.redis.host=redis
spring.redis.port=6377
spring.redis.password=
spring.redis.database=4
```

Please note that the port number I configured is `6377`, but the error logs after startup are still as follows:

```
Connection refused: localhost/127.0.0.1:6379
```

**Comment by Nomango** [comment]
The jdbc session is only available on my local machine, and it is still not effective in my cluster environment.

 When I added `spring.session.store-type=redis` property only, the error log was

```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "spring_session" does not exist
```

And after I added `spring.session.jdbc.initialize-schema=always`, the previous error log reappeared.

```
INFO 9 --- [nio-8080-exec-7] skills.auth.UserInfoService              : Unexpected/Unauthenticated princial [anonymousUser]
```

**Comment by rmmayo** [comment]
All SkillTree instances in your clustered system must share the same PostgreSQL instance (i.e., each node cannot have their own postgres database), regardless if you are using it to store your HTTP session or not, so I'm assuming each node *does* share a single PostgreSQL database?

You initially said that JDBC *was* working, but later said it is not so I'm a little confused.  I suggested your Redis configuration might be incorrect because you had received a connection refused error. 

The message `Unexpected/Unauthenticated princial [anonymousUser]` you are seeing in the logs is not necessarily an ERROR message, this INFO message will normally occur when a user that is not logged in first attempts to access a protected resource such as the `userInfo` api (it should not happen after a successful `performLogin` and the two requests should share the same `JSESSIONID` however).

I would need more information on your clustered setup to help.  
1. Are you running in a commercial cloud environment, are you using docker swarm, kubernetes, etc.,  
2. Are you using a load balancer to front all requests.  
3. Were you running in a clustered environment before upgrading to 2.4 and if so were you using Redis as your HTTP session store configuration?  etc.
4. Are you using a singled shared PostgreSQL instance for all nodes in your cluster
5. When using Redis to store the HTTP session, is it a single shared instance all nodes and is each node able to connect
6. Are you still experiencing the initial problem of receiving a successful 200 response from perform login, followed by a `null` response and different JSESSIONID, or is the problem different now?

I highly recommend using JDBC to store the HTTP session in a clustered environment due to its simplicity, and since a shared PostgreSQL instance is already required there no need to run a separate product.

**Comment by rmmayo** [comment]
@Nomango thank you for the example!  I was able to reproduce the error, and have determined the problem.

In SkillTree 2.4 we upgraded to Spring Boot 3.  Spring Boot 3 has moved the configuration properties for Redis from `spring.redis` to `spring.data.redis` as noted in the [Spring Boot 3.0 migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#redis-properties).

I have updated the [SkillTree documentation](https://skilltreeplatform.dev/dashboard/install-guide/config.html#httpstore) to reference the new property names as well as recommending JDBC as the recommended HTTP Session Store.

Have a great day and thank you for participating in the SkillTree community!
