### ISSUE TITLE
Improve "Applied skill events per day" on skill's metrics page to just be "Skill Events Per Day"

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#284]
Improve ``Applied skill events per day`` on skill's metrics page to just be "Skill Events Per Day"; updated version of this charts will have 2 series: 
- All events from ``UserEvent`` table
- Events that contributed points from ``UserPerformedSkill`` table

In addition add time window control for ``30 days`` (default), ``6 months``, ``1 year``

**Comment by rmmayo** [comment]
it seems like the zero fill is not working properly for "All Skill Events" (unless this is intentional?).  see the following screen shots from integration:

![image](https://user-images.githubusercontent.com/47030042/107219845-a3b36a80-69df-11eb-8aa5-9e232cc1db73.png)

![image](https://user-images.githubusercontent.com/47030042/107220017-d6f5f980-69df-11eb-87cd-e46cf0241151.png)

**Comment by rmmayo** [comment]
ticket #319 was created to fix the missing zero entries in the "Applied Skill Events" data set.
