### ISSUE TITLE
Duplicate emails are sent when user requests points via self-reporting skill

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#425]
Duplicate emails are sent when user requests points via self-reporting skill

**Comment by rmmayo** [comment]
spent pretty much all day tracking this down :roll_eyes:   -  it seems the duplicate emails are because the test projects on our integration test instance is seeded with 4 project admins, the 3 main developers and another email that is aliased to the 3 main developers.  This is why we are getting two emails.
