### ISSUE TITLE
Add OAuth2 support for Keycloak

### ISSUE THREAD

**Issue by shanesoh** [NationalSecurityAgency/skills-service#463]
SkillTree has support for various social and SaaS identity providers like Google, GitHub and Auth0. However the only supported self-hosted OAuth2 provider is GitLab.

Keycloak is a popular open source identity and access management solution commonly used in self-hosted and on-premise environments. It'll be good for SkillTree to have OAuth2 support for Keycloak.

**Comment by rmmayo** [comment]
Hello @shanesoh - Thanks so much for your contribution.  Keycloak has been something we've been wanting to add support for so this is very much appreciated.  

If you have a sec, would you mind adding some integration tests?  We typically require testing for new features, and you can check out our contribution guide [here](https://code.nsa.gov/skills-docs/contribution/#bugs-and-feature-requests) for more info.

One idea for testing keycloak would be to setup another github workflow similar to our [Continuous Integration with OAuth](https://github.com/NationalSecurityAgency/skills-service/blob/master/.github/workflows/build-and-test-oauth.yml) workflow, but instead of using hydra as the oauth server, maybe there is a simliar keycloak docker container we could run?  After doing  a quick google search, [Keycloak Testcontainer](https://github.com/dasniko/testcontainers-keycloak) looks like a possible candidate but if there's another one you prefer feel free to use that.

**Comment by rmmayo** [comment]
> Hello @shanesoh - Thanks so much for your contribution. Keycloak has been something we've been wanting to add support for so this is very much appreciated.
> 
> If you have a sec, would you mind adding some integration tests? We typically require testing for new features, and you can check out our contribution guide [here](https://code.nsa.gov/skills-docs/contribution/#bugs-and-feature-requests) for more info.
> 
> One idea for testing keycloak would be to setup another github workflow similar to our [Continuous Integration with OAuth](https://github.com/NationalSecurityAgency/skills-service/blob/master/.github/workflows/build-and-test-oauth.yml) workflow, but instead of using hydra as the oauth server, maybe there is a simliar keycloak docker container we could run? After doing a quick google search, [Keycloak Testcontainer](https://github.com/dasniko/testcontainers-keycloak) looks like a possible candidate but if there's another one you prefer feel free to use that.

Hi @shanesoh - on second thought, I think implementing a whole new github workflow just for keyclock is overkill.  Could you please just add a simple test to the `skills.auth.OAuth2UserConverterServiceSpec` testing the `KeycloakUserConverter`?

**Comment by antonionardella** [comment]
Hello,

can anyone point me toward the documentation for setting up Keycloak as identity provider?
I am looking at [this page](https://skilltreeplatform.dev/dashboard/install-guide/config.html#oauth-support-pass-auth-mode-only) and trying to replicate GitLabs configuration without real success

Thanks

**Comment by rmmayo** [comment]
Hello @antonionardella - the Keycloak support in SkillTree was added by a non-core contributor and the core team has not actually integrated Keycloak as an identity provider before. I suspect that the setup would be similar to the providers listed on the [documentation page](https://skilltreeplatform.dev/dashboard/install-guide/config.html#user-info-service-pki-mode-only).  

If you have time and would like to, we would welcome you to test Keycloak integration and submit a PR to the [skills-docs repo](https://github.com/NationalSecurityAgency/skills-docs).
