### ISSUE TITLE
Provide ability to ``copy`` a skill

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#519]
On the ``Skills`` page add a button for each skill to bring up a ``New Skill`` dialog with values prepopulated from the selected skill

**Comment by sudo-may** [comment]
PR https://github.com/NationalSecurityAgency/skills-service/pull/578

**Comment by rmmayo** [comment]
@mosefer - everything looks good.  One thing that seemed a bit strange was the the copied skill will automatically fill in the skillId field as `copy_of_<origSkillId>`, but once you change the name in anyway, the skillId field will immediately change to camel case (i.e. `copyOfOrigSkillId2`).  

Not sure warrants changing it or not - if you think so go ahead and change it an I can re-test, otherwise feel free to close the ticket.
