### ISSUE TITLE
Admin: remember last sort order on tables 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#524]
consider using (local storage)

**Comment by dwalizer** [comment]
PR: #1691

**Comment by mosefer** [comment]
It looks like the sort preference for only the most recently interacted with table is retained. If table A is sorted, the sort preference is retained however as soon as another, different table, is sorted, any sort preference for table A is lost.

To reproduce:

1. Navigate to the default Administrator view
2. Create enough projects so that a table view is rendered
3. Sort one of the columns such that the sort order is different from the default order
4. Navigate away and back to Projects without sorting any other tables - **sort preference is retained**
5. Navigate to one of the subjects within a project
6. Sort by any column that changes the default order
7. Navigate back to the table of all projects - **sort preference has been lost**

**Comment by dwalizer** [comment]
PR: #1730
