### ISSUE TITLE
API seems overly complex, not sure how to authenticate and add points

### ISSUE THREAD

**Issue by cybrpimp** [NationalSecurityAgency/skills-service#600]
We are trying to figure out the API but it seems overly complex and not like a simple API Endpoint.  Is there any more documentation or advice you can offer as we have been trying to use this for weeks now and unfortunately out of options.

**Comment by rmmayo** [comment]
hi @cybrpimp - sorry to hear you are having trouble.  The authentication flow for [password based](https://code.nsa.gov/skills-docs/dashboard/install-guide/installModes.html#password-auth-mode) SkillTree installation requires the client app to implement *their own* server side endpoint.  This endpoint uses the project's client id and secret to obtain a token on behalf of the user logged into the client application.  

The diagram below shows the typical flow: 

![image](https://user-images.githubusercontent.com/47030042/117546139-00322000-aff7-11eb-855b-7214b6ca712c.png)

1. User authenticates with the client web application.
2. The client web app requests a user token from their own backend server.
3. The client backend server uses the project client id and secret to obtain the user's token from the SkillTree backend server, which is sent back to the client web app.
4. The client web app reports skills to the SkillTree backend server.  The token obtained in steps 2-3 is sent as an HTTP Header with each request.

The details for implementing your own endpoint to retrieve a user token is documented [here](https://code.nsa.gov/skills-docs/skills-client/auth.html).  When configuring the SkillTree client library, use this endpoint URL for the `authenticator` property on the `SkillsConfiguration.configure` call.  Further documentation can be found [here](https://code.nsa.gov/skills-docs/skills-client/js.html#skills-configuration).

Also, the [Quick Start Guide](https://code.nsa.gov/skills-docs/dashboard/install-guide/quickStart.html#_1-prerequisites) shows a complete working example.

I hope this helps!  Good luck!

**Comment by cybrpimp** [comment]
No did not help. As I said it is OVERLY COMPLEX.

We work with APIs all day from Dropbox and many others and never had this many problems.

**Comment by mosefer** [comment]
Could you provide a specific example of what you're trying to accomplish? That we may be able to better point you in the right direction. It might help if we take it step by step as to exactly what you've tried so far and exactly what you're attempting to do.

**Comment by cybrpimp** [comment]
Hey @mosefer , yes we just need a simple API endpoint that can be used to authenticate with a token & Add Points to Skilltree from our custom application.

For example, Redmine is one of the applications we use the API to integrate with and it is a simple process to authenticate and access.

https://www.redmine.org/projects/redmine/wiki/rest_api#Authentication

**Comment by mosefer** [comment]
@cybrpimp  - will Skill events be reported via user interactions with a webapp or via REST interactions with a SkillTree instance? The authentication mechanism that SkillTree uses to report skills is a Oauth2 temporary client token approach. Depending on which integration approach you're taking, we could provide some guidance.

**Comment by mosefer** [comment]
@cybrpimp  thanks and no worries, I'm going to take a step back to see if I can provide some guidance on setup and how it all fits together. We're also in the process of updating our documentation to hopefully make things a little clearer. So I'll start with the recommended implementation approach for your use case (integrating SkillTree into a webapp) and we can use that as a basis to discuss other approaches as necessary or where things aren't working for you. I may well re-state some things that you've already done but I think it'll help to get us all onto the same page.

Recommended approach:
1. Stand up an instance of the SkillTree dashboard/service - the easiest way is to use the [available docker container](https://hub.docker.com/r/skilltree/skills-service)
2. Create a Project using the SkillTree dashboard - this will contain the specific Skills you want users to accomplish (number of required repetitions, time between point awards, etc). The important thing to note here are the Skill IDs as these are what your webapp will report as users perform those actions.
    1. It's important to take note of the ```client-id``` and ```client-secret``` as we'll need these later - when viewing the Project you created in the SkillTree dashboard, these are available under the ```Access``` menu on the left: 
![image](https://user-images.githubusercontent.com/61209506/118012583-39cc9900-b31f-11eb-9ce5-0bd56c2a4cba.png)
3.  In your webapp's backend, create an authentication endpoint, something like ```/users/{userid}/token``` - this end point, in YOUR webapp's backend is going to make a REST request to the SkillTree instance from step 1 and include your ```client-id``` and ```client-secret``` from earlier. It might seem convoluted but things are done this way so that your ```client-id``` and ```client-secret``` are never exposed to the browser. The details of this are covered in [our docs](https://code.nsa.gov/skills-docs/skills-client/auth.html) but we definitely want to know if we haven't done a proper job of it yet.
4. Next is to integrate reporting of Skill events (i.e., when a user performs an action within your application that you would like them to earn points for). We provide npm libraries supporting [Angular](https://www.npmjs.com/package/@skilltree/skills-client-ng), [React](https://www.npmjs.com/package/@skilltree/skills-client-react), [Vue](https://www.npmjs.com/package/@skilltree/skills-client-vue), and plain [Javascript](https://www.npmjs.com/package/@skilltree/skills-client-js). These libraries make it relatively easy to report back to the SkillTree service/dashboard when a user performs an event you'd like them to receive points for. Docs covering reporting of Skill events in [Vue.js for example](https://code.nsa.gov/skills-docs/skills-client/vuejs.html#skill-event-reporting).
    1. Note that before you start interacting with the SkillTree npm libraries in your webapp, you need to call [SkillsConfiguration.configure](https://code.nsa.gov/skills-docs/skills-client/vuejs.html#skills-configuration) when the page is loaded. In this case ```serviceUrl``` will point to the SkillTree instance deployed in Step 1. and ```authenticator``` will point to the endpoint created in YOUR webapp in step 3.
5. Now that you've got reporting of Skill events integrated you can integrate a display of the user's Ranking, the Skills they can accomplish, how many points they currently have, etc very easily and quickly. We provide an out-of-the box display component that gets you that display without any further work and can be integrated directly into your application. Example for [Vue.js](https://code.nsa.gov/skills-docs/skills-client/vuejs.html#skills-display) but each of the framework libraries we provide as well as the native Javascript libraries provide the same component.


So the biggest step that seems convoluted at the outset is the oauth2 authentication flow between **your** webapp's backend and the SkillTree instance. Now that we've got the recommended integration flow laid out in one place, what parts are you finding not to work for you? Part of the challenge is that we don't want to expose your Project's client-secret to the web-client as that would allow any user to potentially masquerade as any other use in the context of reporting Skill events and the out-of-the box display component that we provide.

**Comment by ceefour** [comment]
I also wrote a tutorial for this, hope this helps: https://about.lovia.life/docs/peopleops/skilltree/

**Comment by ceefour** [comment]
Thank you @mosefer for your clear explanation. Truly appreciate it.
