### ISSUE TITLE
Add Project Name to My Badges display

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#837]

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/839

**Comment by rmmayo** [comment]
The project name is showing in the "BADGE CATALOG":
![image](https://user-images.githubusercontent.com/47030042/133769687-2baa1de5-7931-4151-9e5d-39a4ae6bd6da.png)


...but it is not showing in the "MY EARNED BADGES" section:

![image](https://user-images.githubusercontent.com/47030042/133769591-2822fe65-d89f-448a-bd66-03d2fd71709c.png)

I'm not sure if this is intentional or not?

**Comment by sudo-may** [comment]
@rmmayo @mosefer that's a good point, i don't think we've thought of it as a part of this ticket but seems like an oversight - I say we should add to the earned badges as well

**Comment by mosefer** [comment]
@rmmayo  @sudo-may - project name added to achieved badges in #846, closing this ticket.
